config/routes.rb
Rails.application.routes.draw do

  root  to: 'static_pages#index'

  get 'about', to: 'static_pages#about'
  get 'contact_us', to: 'static_pages#contact'

  resources :contacts
  resources :users, only: [:new, :create, :show, :edit, :update]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}
  validates :phone, presence: true, length: {maximum: 24}
  validates :description, presence: true, length: {minimum: 10}
  validates :status, presence: true
  validates :picture, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: {maximum: 46}
  validates :status, presence: true
  validates :password, length: {minimum: 6}
  validates :email, presence: true, length: {maximum: 80},
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: true }
  
  has_many :contacts
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
  
  private
    def require_logged_in_user
      unless user_signed_in?
        flash[:danger] = "Área restrita, por favor realize o login!"
        redirect_to login_path
      end

    end
    
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  before_action :require_logged_in_user
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :phone, :description, :status, :picture)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to user_path(current_user) if user_signed_in?
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
       sign_in(user)
       flash[:success] = 'Login efetuado com sucesso!'
       redirect_to contacts_path
    else
      flash.now[:danger] = 'Email ou senha inválidos'
      render 'new'
    end

  end

  def destroy
    sign_out
    flash[:success] = 'Logout efetuado com sucesso!'
    redirect_to login_path
  end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @page_title = "Página inicial"
  end

  def about
    @page_title = "Sobre nós"
  end

  def contact
    @page_title = "Contatos"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_logged_in_user, only: [:show, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Usuário cadastrado com sucesso!'
      redirect_to root_url
    else
      render 'new'
    end
  end 

  def show
  end

  def edit
  end
  
  def update
    if current_user.update(user_params)
      flash[:success] = 'Dados atualizados com sucesso'
      redirect_to contacts_path
    else
      render 'edit'
    end
  end
  

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :status, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
  end

  def current_user
    @current_user||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= bootstrap_form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.text_field :name %>

  
    <%= form.text_field :phone %>
  

  
    
    <%= form.text_area :description %>
  

  
    
    <%#= form.text_field :status %>
    <%= form.select :status, [["Ativo", 1], ["Inativo", 0]], { label: "Selecione um status:", wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, { class: "selectpicker" } %>
  

  
    
    <%= form.text_field :picture %>
  

  <div class="actions">
    <%= form.submit 'Salvar', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="py-5 bg-light">
  <div class="container">

    <div class="row">

      <h1>Editing Contact</h1>

      <%= render 'form', contact: @contact %>

      <%= link_to 'Show', @contact %> |
      <%= link_to 'Back', contacts_path %>
      
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">
      <p id="notice"><%= notice %></p>

      <h1>Contacts</h1>

      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Phone</th>
              <th>Description</th>
              <th>Status</th>
              <th>Picture</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @contacts.each do |contact| %>
              <tr>
                <td><%= contact.name %></td>
                <td><%= contact.phone %></td>
                <td><%= contact.description %></td>
                <td><%= contact.status %></td>
                <td><%= contact.picture %></td>
                <td><%= link_to 'Show', contact %></td>
                <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
                <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= link_to 'New Contact', new_contact_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="py-5 bg-light">
  <div class="container">

    <div class="row">

      <h1>New Contact</h1>
    </div>

    <div class="row">

      <%= render 'form', contact: @contact %>

    </div>

    <div class="row">
      <%= link_to 'Back', contacts_path %>
    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Name:</strong>
        <%= @contact.name %>
      </p>

      <p>
        <strong>Phone:</strong>
        <%= @contact.phone %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @contact.description %>
      </p>

      <p>
        <strong>Status:</strong>
        <%= @contact.status %>
      </p>

      <p>
        <strong>Picture:</strong>
        <%= @contact.picture %>
      </p>

      <%= link_to 'Edit', edit_contact_path(@contact) %> |
      <%= link_to 'Back', contacts_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Contact List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    

     <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    

  </head>

  <body>
    <%= render partial: 'layouts/components/header' %>
      
    <main role="main">

      <%= yield %>

    </main>

    <%= render partial: 'layouts/components/footer' %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script>
      feather.replace()
    </script>
  </body>
</html>

app/views/layouts/components/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Voltar ao topo</a>
    </p>
    <p>Quer saber mais <%= link_to  "Sobre nós?", about_path %> Que entrar em <%= link_to  "Contato?", contact_us_path %>,  Ficamos felizes em ter você aqui.</p>
  </div>
</footer>

app/views/layouts/components/_header.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><%= link_to "Sobre nós", about_path, class: 'text-white' %></li>
            <li><%= link_to "Contate-nos", contact_us_path, class: 'text-white' %></li>
            <li><%= link_to "Nosso site", 'https://rltecno.com.br', class: 'text-white', target: '_blank' %></li>
            
            <% if !user_signed_in? %>

              <li><%= link_to "Cadastrar-se", new_user_path, class: 'text-white' %></li>
              
              <li><%= link_to "Login", login_path, class: 'text-white' %></li>
            <% else %>
              <li><%= link_to "Logout", logout_path, method: :delete, class: 'text-white' %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
     
      <%= link_to  root_path, class: 'navbar-brand d-flex align-items-center' do %>
        <!--<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="20px" height="20px" fill="#FFF" stroke="currentColor" viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve">
          <g>
            <rect x="156" y="434" width="299" height="45"/>
            <rect x="55" y="434" width="56" height="45"/>
          </g>
          <g>
            <rect x="156" y="334" width="299" height="45"/>
            <rect x="55" y="334" width="56" height="45"/>
          </g>
          <g>
            <rect x="55" y="234" width="56" height="45"/>
            <rect x="156" y="234" width="299" height="45"/>
          </g>
          <g>
            <rect x="55" y="134" width="56" height="45"/>
            <rect x="156" y="134" width="299" height="45"/>
          </g>
          <g>
            <rect x="55" y="34" width="56" height="45"/>
            <rect x="156" y="34" width="299" height="45"/>
          </g>
        </svg>-->
        <%= image_tag  "https://img.icons8.com/cute-clipart/64/000000/add-list.png", width: '40px' %>
        <strong> &nbsp; Contact List</strong>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/static_pages/_jumbotron.html.erb
<section class="jumbotron text-center">
  <div class="container">

    <% flash.each do |message_type, message| %>
      <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: alert do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= message %>
      <% end %>
    <% end %>

    <p>
      <%= link_to  "Criar Conta", new_user_path, class: 'btn btn-primary my-2' %>
    </p>

    <h1>Contact List App</h1>
    <p class="lead text-muted">Crie e gerencie sua lista d contatos em um só lugar.</p>
    <p>
      <%= link_to  "Lista de contatos", contacts_path, class: 'btn btn-success my-2' %>
      <%= link_to  "Cadastrar novo", new_contact_path, class: 'btn btn-secondary my-2' %>
    </p>
  </div>
</section>

app/views/static_pages/about.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    About page 
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    Contact page 
  </div>
</div>

app/views/static_pages/index.html.erb
<%= render partial: 'static_pages/jumbotron' %>

<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">

      <% 6.times.each do |users| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      
    </div> <!-- end row -->

  </div>
</div>

app/views/users/_form.html.erb
<%= bootstrap_form_with(model: user, local: true) do |form| %>
  

    <%= form.text_field :name %>

    <%= form.email_field :email %>
  
    <%= form.password_field :password %>
    
    <%= form.password_field :password_confirmation %>
    
    <%#= form.text_field :status %>
    <%= form.select :status, [["Ativo", 1], ["Inativo", 0]], { label: "Selecione um status:", wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, { class: "selectpicker" } %>
    
  <div class="actions">
    <%= form.submit 'Salvar', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="py-5 bg-light">
  <div class="container">

    <div class="row">

      <h1>Editar Conta</h1>
    </div>

    <div class="row">

      <%= render 'form', user: @user %>

    </div>

   
  </div>
</div>

app/views/users/new.html.erb
<div class="py-5 bg-light">
  <div class="container">

    <div class="row">

      <h1>Cadastrar-se</h1>
    </div>

    <div class="row">

      <%= render 'form', user: @user %>

    </div>

   
  </div>
</div>

app/views/users/show.html.erb
<section class="jumbotron text-center">
  <div class="container">

    <% flash.each do |message_type, message| %>
      <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: alert do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= message %>
      <% end %>
    <% end %>

    <p>
      <%= link_to  "Editar Conta", edit_user_path, class: 'btn btn-primary my-2' %>
    </p>

    <h1>Olá <%= current_user.name %></h1>
    <p class="lead text-muted">Crie e gerencie sua lista d contatos em um só lugar.</p>
    <p>
      <%= link_to  "Lista de contatos", contacts_path, class: 'btn btn-success my-2' %>
      <%= link_to  "Cadastrar novo", new_contact_path, class: 'btn btn-secondary my-2' %>
    </p>
  </div>
</section>